// Generated from website/memories.js: the only files the proxy will serve.
export const ALLOWED = new Set([
 "Audio/21Feb1101.mp3",
 "Audio/25Feb1101.mp3",
 "Audio/28Feb1101.mp3",
 "Audio/Correct.mp3",
 "Audio/DeDeAmma.mp3",
 "Audio/HBD.mp3",
 "Audio/Mango.mp3",
 "Audio/Mani_Viji.mp3",
 "Audio/Meena_Mohan.mp3",
 "Audio/Onion.mp3",
 "Audio/Soundclip03.mp3",
 "Audio/Soundclip04.mp3",
 "Audio/Soundclip05.mp3",
 "Audio/Soundclip06.mp3",
 "Audio/Soundclip08.mp3",
 "Audio/Soundclip13.mp3",
 "Audio/Soundclip24.mp3",
 "Audio/Soundclip25.mp3",
 "Audio/Soundclip26-01.mp3",
 "Audio/Soundclip28.mp3",
 "Audio/Soundclip29.mp3",
 "Audio/ThathaAachi.mp3",
 "Audio/karan.mp3",
 "Mama/Mama-Tape-01.mp3",
 "Mama/Mama-Tape-02.mp3",
 "Mama/Mama-Tape-03.mp3",
 "Mama/Mama-Tape-04.mp3",
 "Mama/Mama-Tape-05.mp3",
 "Mama/Mama-Tape-06.mp3",
 "Mama/Mama-Tape-07.mp3",
 "Mama/Mama-Tape-08.mp3",
 "Video/15 Feb11 01 [kure2T0nbk4].mp4",
 "Video/19022011208 [e0d9M_oelbM].mp4",
 "Video/19022011209 [nlya5LKy5O4].mp4",
 "Video/24042011251 [T7MSm3hNCrY].mp4",
 "Video/25042011252 [M2akrDeoqMo].mp4",
 "Video/30012011045 [tqA-tpnakbA].mp4",
 "Video/3rd Birthday Party - Cake [qdyYNdaoYuo].mp4",
 "Video/3rd Birthday Party - Game 1 [GeZKe47ylH8].mp4",
 "Video/3rd Birthday Party - Game 2 [fjwC7lYGOzg].mp4",
 "Video/3rd Birthday Party - PinTheTail [mCPJR8Kki9Q].mp4",
 "Video/3rd Birthday Party - Pinata [0UhuX0JFavE].mp4",
 "Video/3rd Birthday Present 1 [EzhM0WE2WPE].mp4",
 "Video/3rd Birthday Present 2 [x2z-7EpwUXg].mp4",
 "Video/@ School with Jeeta Teacher [v_4YoLTnGMI].mp4",
 "Video/@Home [6sqNfRQghSo].mp4",
 "Video/@SnowPlanet [RZY8J3cV6RM].mp4",
 "Video/@SnowPlanet [WBnYD_zT9U4].mp4",
 "Video/ABC Song [DbWMKEAFLJ8].mp4",
 "Video/Adam with Kalla Alugai [iYc8lygpKgo].mp4",
 "Video/Angry Birds [Y3CUu3OmD60].mp4",
 "Video/Animals [AqbSkbdxZic].mp4",
 "Video/Anthakshari [z_ljBbm_HWs].mp4",
 "Video/At Playgroup 2 [LEBwZ1VuALc].mp4",
 "Video/At Zoo [6hS3YSJlfME].mp4",
 "Video/Balancing Bridge @ Playschool [mIW_YCu493Q].mp4",
 "Video/Bike Riding - Day 2 [Xiy43tjJku8].mp4",
 "Video/Birthday @School [cHVYA2vcIlY].mp4",
 "Video/Birthday Morning 1 [IRa4pck6bSo].mp4",
 "Video/Birthday Morning 2 [pU2ttNtoYbg].mp4",
 "Video/Birthday Morning 3 [1daXVvwjYnw].mp4",
 "Video/Blah Blah Blah Time [4if6M2Dm1As].mp4",
 "Video/Bouncy Slide [md3WjmOB7SE].mp4",
 "Video/Carousel @ Devonport Ferry Terminal [3cVF4BEZxnU].mp4",
 "Video/Caught Milo-Handed [5850IfaQKkU].mp4",
 "Video/Chat @ Home [Fr3hZFaFpQc].mp4",
 "Video/Chat About Easter Show [gP7jIsAOTag].mp4",
 "Video/Climbing @ Western Springs Playground [T8tkHKaDY3A].mp4",
 "Video/Computer Work At Zoo [S_Zqz0EzHuI].mp4",
 "Video/Dance Class Last Day of the Term Certificate [yJvhpjwmGD4].mp4",
 "Video/Dance Class Last Day of the Term [lBR1HOPllfE].mp4",
 "Video/Diego Diego Diego ADAM [XH4gMIXFUT8].mp4",
 "Video/Easter 2012  Egg Hunt [4F-o4aQarxE].mp4",
 "Video/Easter 2012 Egg Hunt Surprise [0IZuo-bFFbI].mp4",
 "Video/Easter 2012 Happy Easter [9oOWFmMsa1M].mp4",
 "Video/Easter 2012 Yumm Yumm [zvqmezdnu7o].mp4",
 "Video/Easter Egg Painting at Mall [U8fzMJwA6F0].mp4",
 "Video/Facepainting at Whitcoulls Easter Fun... [Cy5m7m30M5U].mp4",
 "Video/First Birthday Party [ZA7NZ5kfKVs].mp4",
 "Video/Helping with Rubbish Disposal 2 [jBLnkE0OCCo].mp4",
 "Video/I Love Barney!!! [d5VRxssYQno].mp4",
 "Video/I Love You Song [-96b9X603VM].mp4",
 "Video/Incy Wincy Spider Song [d8nUkcreXb8].mp4",
 "Video/Keyboard Player [lC9Vg674vOg].mp4",
 "Video/Kural [jHKqDWkEsz8].mp4",
 "Video/Love You KILI [_1kYSFRgspg].mp4",
 "Video/Mama's new Dishwasher [EpGS4ZgZBJQ].mp4",
 "Video/Mama, I am Flamingo [G_6fUAxrPhc].mp4",
 "Video/Mountain Climbing [BfisxBF5JBQ].mp4",
 "Video/Playgroup 1 [IkY7rubKzf4].mp4",
 "Video/Playgroup 2 [vXRJ6huTjfM].mp4",
 "Video/Playgroup 3 [RqkY9xmJZv0].mp4",
 "Video/Polkadot Girl [cqO6TxKt5N0].mp4",
 "Video/Reading ＂Just Like My Dad＂ (her next favorite) book with Mama [awA6Eh5ovto].mp4",
 "Video/Reading ＂Just Like My Mum＂ (her favorite) book on her own [AZYlNfo-5YI].mp4",
 "Video/Reading ＂Just Like My Mum＂ (her favorite) book with Mama [_a8e4uIzs1c].mp4",
 "Video/Rhymes [YNzOhnb8fqM].mp4",
 "Video/Riding New Bike on 9th Apr [JRFfkWrAsi4].mp4",
 "Video/Riding Scooter on 9th Apr [JRXcqdUDWKo].mp4",
 "Video/Rock Climbing At Zoo [OAzQ9nM9G3s].mp4",
 "Video/Rope Walking At Zoo [CaWXoGB_F_I].mp4",
 "Video/Royal Easter Show 2012. Bouncy Slide. [AO2ovwEZIdI].mp4",
 "Video/Royal Easter Show 2012. Carousal. [-lvre7J5GbQ].mp4",
 "Video/Sahana in Durra!! [HR7HslRTNmk].mp4",
 "Video/Second Birthday Party [JDY7JWtumpE].mp4",
 "Video/Sleeptime at Nite [FfwOAn_Aj4c].mp4",
 "Video/Swinging @ Western Springs Playground [ewA-mgJ2-Gs].mp4",
 "Video/That's WRONG Dada [RmVfsCiCRpE].mp4",
 "Video/VIDEO0040 [IEXDMyNIDco].mp4",
 "Video/VIDEO0041 [rnTrZ26PmVo].mp4",
 "Video/Washing Hands @ Playschool with new friend [2T0iEKyNzUU].mp4"
]);
