// Generated: titles & captions for each memory. Files live in SharePoint (Papa's Memories › Documents).
window.MEMORIES = {
 "cats": [
  {
   "id": "tapes",
   "emoji": "🎙️",
   "name": "Little Voice Tapes",
   "blurb": "Tiny voice, big personality. Press play and time-travel.",
   "color": "#ff8fab",
   "count": 23
  },
  {
   "id": "mama",
   "emoji": "👩‍👧",
   "name": "Mama's Memory Tapes",
   "blurb": "One long treasured recording, snipped into bite-size tapes. Grab a cuppa and listen.",
   "color": "#ffc8dd",
   "count": 8
  },
  {
   "id": "mamawedding",
   "emoji": "💍",
   "name": "Mama's Wedding Day",
   "blurb": "Dada and Mama's big day on three old discs: family, rituals, the feast and the reception.",
   "color": "#ffd6a5",
   "count": 52
  },
  {
   "id": "mamaceremony",
   "emoji": "🌺",
   "name": "Mama's Coming-of-Age Ceremony",
   "blurb": "Silk, jasmine, blessings and a big family feast, from two old VHS tapes.",
   "color": "#caffbf",
   "count": 28
  },
  {
   "id": "keepsakes",
   "emoji": "🖼️",
   "name": "Keepsakes & Photos",
   "blurb": "Her own handwriting, and photos worth framing.",
   "color": "#a0c4ff",
   "count": 3
  },
  {
   "id": "art",
   "emoji": "🖌️",
   "name": "Her Drawing Board",
   "blurb": "Drawings she makes on the iPad: characters, dragons and sketchbook pages.",
   "color": "#bdb2ff",
   "count": 65
  },
  {
   "id": "birthday",
   "emoji": "🎂",
   "name": "Cake, Candles & Party Hats",
   "blurb": "Wishes, presents, games and a lot of cake.",
   "color": "#ffb347",
   "count": 13
  },
  {
   "id": "easter",
   "emoji": "🐣",
   "name": "Egg Hunts & Easter Shows",
   "blurb": "Chocolate eggs, face paint and carousel rides.",
   "color": "#b5e48c",
   "count": 9
  },
  {
   "id": "zoo",
   "emoji": "🦁",
   "name": "Zoo Days & Big Adventures",
   "blurb": "Climbing, swinging, sliding, riding. Go, go, go!",
   "color": "#8ecae6",
   "count": 14
  },
  {
   "id": "school",
   "emoji": "🎒",
   "name": "Playgroup, Playschool & Dance",
   "blurb": "New friends, balancing bridges and dance-class stars.",
   "color": "#cdb4db",
   "count": 9
  },
  {
   "id": "songs",
   "emoji": "🎵",
   "name": "Songs, Rhymes & Storytime",
   "blurb": "Sing-alongs, rhymes, Kural and favourite books.",
   "color": "#ffd166",
   "count": 12
  },
  {
   "id": "home",
   "emoji": "🏠",
   "name": "Giggles at Home",
   "blurb": "The everyday moments that turned out to be the best ones.",
   "color": "#f4a261",
   "count": 15
  },
  {
   "id": "phone",
   "emoji": "📱",
   "name": "Old Phone Treasures",
   "blurb": "Straight off the 2011 mobile phone: grainy, precious, perfect.",
   "color": "#90e0ef",
   "count": 8
  }
 ],
 "items": [
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Correct.mp3",
   "cat": "tapes",
   "emoji": "✅",
   "title": "Correct!",
   "caption": "Correct! (No arguments accepted.)",
   "added": "2026-09-15",
   "slug": "correct"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "DeDeAmma.mp3",
   "cat": "tapes",
   "emoji": "🍼",
   "title": "De De Amma",
   "caption": "“De De Amma!” A little voice, loud and clear.",
   "added": "2026-09-15",
   "slug": "de-de-amma"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "HBD.mp3",
   "cat": "tapes",
   "emoji": "🎂",
   "title": "Happy Birthday!",
   "caption": "Happy birthday! 🎈 Press play for the birthday wishes.",
   "added": "2026-09-15",
   "slug": "happy-birthday"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "karan.mp3",
   "cat": "tapes",
   "emoji": "👦",
   "title": "Karan",
   "caption": "Karan! A tiny voice clip, big smiles.",
   "added": "2026-09-15",
   "slug": "karan"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Mango.mp3",
   "cat": "tapes",
   "emoji": "🥭",
   "title": "Mango!",
   "caption": "Mango! The fruit, the word, the legend.",
   "added": "2026-09-15",
   "slug": "mango"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Mani_Viji.mp3",
   "cat": "tapes",
   "emoji": "💌",
   "title": "Mani & Viji",
   "caption": "Mani and Viji, in one little voice clip.",
   "added": "2026-09-15",
   "slug": "mani-and-viji"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Meena_Mohan.mp3",
   "cat": "tapes",
   "emoji": "💌",
   "title": "Meena & Mohan",
   "caption": "Meena and Mohan, in one little voice clip.",
   "added": "2026-09-15",
   "slug": "meena-and-mohan"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Onion.mp3",
   "cat": "tapes",
   "emoji": "🧅",
   "title": "Onion",
   "caption": "Onion. Say it with feeling!",
   "added": "2026-09-15",
   "slug": "onion"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "ThathaAachi.mp3",
   "cat": "tapes",
   "emoji": "👴👵",
   "title": "Thatha & Aachi",
   "caption": "Thatha and Aachi, in one little voice clip. 💛",
   "added": "2026-09-15",
   "slug": "thatha-and-aachi"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip03.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #03",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-03"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip04.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #04",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-04"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip05.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #05",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-05"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip06.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #06",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-06"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip08.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #08",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-08"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip13.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #13",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-13"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip24.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #24",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-24"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip25.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #25",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-25"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip26-01.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #26-01",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-26-01"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip28.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #28",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-28"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "Soundclip29.mp3",
   "cat": "tapes",
   "emoji": "📼",
   "title": "Voice Tape #29",
   "caption": "A mystery tape from the voice archive. Who knows what she'll say? Press play!",
   "added": "2026-09-15",
   "slug": "voice-tape-29"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "21Feb1101.mp3",
   "cat": "tapes",
   "emoji": "📅",
   "title": "Voice Tape · 21 Feb 2011",
   "caption": "Recorded 21 February 2011.",
   "added": "2026-09-15",
   "slug": "voice-tape-21-feb-2011",
   "when": "21 February 2011"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "25Feb1101.mp3",
   "cat": "tapes",
   "emoji": "📅",
   "title": "Voice Tape · 25 Feb 2011",
   "caption": "Recorded 25 February 2011.",
   "added": "2026-09-15",
   "slug": "voice-tape-25-feb-2011",
   "when": "25 February 2011"
  },
  {
   "kind": "audio",
   "folder": "Audio",
   "file": "28Feb1101.mp3",
   "cat": "tapes",
   "emoji": "📅",
   "title": "Voice Tape · 28 Feb 2011",
   "caption": "Recorded 28 February 2011.",
   "added": "2026-09-15",
   "slug": "voice-tape-28-feb-2011",
   "when": "28 February 2011"
  },
  {
   "kind": "audio",
   "folder": "Mama",
   "file": "Mama-Tape-01.mp3",
   "cat": "mama",
   "emoji": "💐",
   "title": "Mama's Tape 1",
   "caption": "Mama's memory tape 1 of 8 (0:47). A recording all of its own.",
   "added": "2026-09-15",
   "slug": "mama-s-tape-1"
  },
  {
   "kind": "audio",
   "folder": "Mama",
   "file": "Mama-Tape-02.mp3",
   "cat": "mama",
   "emoji": "🌸",
   "title": "Mama's Tape 2",
   "caption": "Mama's memory tape 2 of 8 (2:10). A recording all of its own.",
   "added": "2026-09-15",
   "slug": "mama-s-tape-2"
  },
  {
   "kind": "audio",
   "folder": "Mama",
   "file": "Mama-Tape-03.mp3",
   "cat": "mama",
   "emoji": "🌷",
   "title": "Mama's Tape 3",
   "caption": "Mama's memory tape 3 of 8 (3:33). The first part of the long recording. It carries on in the next tape.",
   "added": "2026-09-15",
   "slug": "mama-s-tape-3"
  },
  {
   "kind": "audio",
   "folder": "Mama",
   "file": "Mama-Tape-04.mp3",
   "cat": "mama",
   "emoji": "🌼",
   "title": "Mama's Tape 4",
   "caption": "Mama's memory tape 4 of 8 (2:46). Carries on from the previous tape, and on into the next.",
   "added": "2026-09-15",
   "slug": "mama-s-tape-4"
  },
  {
   "kind": "audio",
   "folder": "Mama",
   "file": "Mama-Tape-05.mp3",
   "cat": "mama",
   "emoji": "🌻",
   "title": "Mama's Tape 5",
   "caption": "Mama's memory tape 5 of 8 (3:17). Carries on from the previous tape, and on into the next.",
   "added": "2026-09-15",
   "slug": "mama-s-tape-5"
  },
  {
   "kind": "audio",
   "folder": "Mama",
   "file": "Mama-Tape-06.mp3",
   "cat": "mama",
   "emoji": "🌺",
   "title": "Mama's Tape 6",
   "caption": "Mama's memory tape 6 of 8 (2:32). Carries on from the previous tape, and on into the next.",
   "added": "2026-09-15",
   "slug": "mama-s-tape-6"
  },
  {
   "kind": "audio",
   "folder": "Mama",
   "file": "Mama-Tape-07.mp3",
   "cat": "mama",
   "emoji": "🪷",
   "title": "Mama's Tape 7",
   "caption": "Mama's memory tape 7 of 8 (3:19). The last part of the long recording.",
   "added": "2026-09-15",
   "slug": "mama-s-tape-7"
  },
  {
   "kind": "audio",
   "folder": "Mama",
   "file": "Mama-Tape-08.mp3",
   "cat": "mama",
   "emoji": "💮",
   "title": "Mama's Tape 8",
   "caption": "Mama's memory tape 8 of 8 (2:18). A recording all of its own.",
   "added": "2026-09-15",
   "slug": "mama-s-tape-8"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-01.mp4",
   "cat": "mamawedding",
   "emoji": "🛕",
   "title": "1. Opening Titles",
   "caption": "The video opens with temple and river scenes, then the family at home. (Wedding disc 1, from 0:00 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-01"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-02.mp4",
   "cat": "mamawedding",
   "emoji": "👧",
   "title": "2. Cousins at Home",
   "caption": "Kids and cousins gather at home while the grown-ups get busy. (Wedding disc 1, from 4:43 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-02"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-03.mp4",
   "cat": "mamawedding",
   "emoji": "🪔",
   "title": "3. Lamp and First Blessings",
   "caption": "The brass lamp is lit and the elders give their blessings. (Wedding disc 1, from 7:49 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-03"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-04.mp4",
   "cat": "mamawedding",
   "emoji": "😊",
   "title": "4. Smiles in Close-Up",
   "caption": "Close-ups of happy faces, and a few shy smiles. (Wedding disc 1, from 12:25 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-04"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-05.mp4",
   "cat": "mamawedding",
   "emoji": "🎁",
   "title": "5. Guests with Gift Trays",
   "caption": "The ladies arrive in their silks, carrying trays of gifts. (Wedding disc 1, from 17:04 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-05"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-06.mp4",
   "cat": "mamawedding",
   "emoji": "🍌",
   "title": "6. Offerings on the Banana Leaf",
   "caption": "Fruit, flowers and coconut laid out while the elders look on. (Wedding disc 1, from 20:40 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-06"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-07.mp4",
   "cat": "mamawedding",
   "emoji": "🕯️",
   "title": "7. Lighting the Lamp Together",
   "caption": "The family gathers around the lamp. (Wedding disc 1, from 24:05 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-07"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-08.mp4",
   "cat": "mamawedding",
   "emoji": "🤝",
   "title": "8. Trays Handed Over",
   "caption": "The men of the family pass the decorated trays. (Wedding disc 1, from 28:39 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-08"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-09.mp4",
   "cat": "mamawedding",
   "emoji": "📺",
   "title": "9. Titles and Prayers by the Lamp",
   "caption": "A title card, then prayers by the lamp. (Wedding disc 1, from 33:01 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-09"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-10.mp4",
   "cat": "mamawedding",
   "emoji": "🌼",
   "title": "10. Offerings by the Lamp",
   "caption": "Everything neatly set out on the leaf, ready for the prayers. (Wedding disc 1, from 36:20 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-10"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-11.mp4",
   "cat": "mamawedding",
   "emoji": "📸",
   "title": "11. Family Photo Outside",
   "caption": "Everyone lines up for a photo in front of the house. (Wedding disc 1, from 39:22 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-11"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-12.mp4",
   "cat": "mamawedding",
   "emoji": "💙",
   "title": "12. Title Song and Blue Silk",
   "caption": "A title song, then close-ups in a beautiful blue silk sari. (Wedding disc 1, from 44:13 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-12"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-13.mp4",
   "cat": "mamawedding",
   "emoji": "💃",
   "title": "13. Laughter with the Girls",
   "caption": "Getting ready, with plenty of giggles. (Wedding disc 1, from 48:39 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-13"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-14.mp4",
   "cat": "mamawedding",
   "emoji": "🏡",
   "title": "14. Friends Arrive",
   "caption": "More relatives and friends drop in. (Wedding disc 1, from 52:39 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-14"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-15.mp4",
   "cat": "mamawedding",
   "emoji": "🥣",
   "title": "15. The Pestle Ritual",
   "caption": "The ladies take turns with the big pestle for a traditional ritual. (Wedding disc 1, from 56:05 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-15"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-16.mp4",
   "cat": "mamawedding",
   "emoji": "🎞️",
   "title": "16. Kids and a Video Montage",
   "caption": "Little ones, big smiles and some very 90s video effects. (Wedding disc 1, from 59:09 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-16"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-17.mp4",
   "cat": "mamawedding",
   "emoji": "💑",
   "title": "17. Dada and Mama's Photo Shoot",
   "caption": "The first photo session together: Dada in a suit, Mama in silk. (Wedding disc 1, from 62:45 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-17"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-18.mp4",
   "cat": "mamawedding",
   "emoji": "💍",
   "title": "18. The Wedding Video Begins",
   "caption": "The wedding title cards appear, with Mama's name on screen. (Wedding disc 2, from 0:00 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-18"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-19.mp4",
   "cat": "mamawedding",
   "emoji": "🏠",
   "title": "19. Titles and the Family Home",
   "caption": "Temple titles, then the family home on the big day. (Wedding disc 2, from 4:20 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-19"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-20.mp4",
   "cat": "mamawedding",
   "emoji": "🙏",
   "title": "20. Blessings Before Leaving",
   "caption": "Blessings at home before heading off. (Wedding disc 2, from 7:56 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-20"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-21.mp4",
   "cat": "mamawedding",
   "emoji": "🚗",
   "title": "21. The Decorated Wedding Car",
   "caption": "The flower-decked car waits outside. (Wedding disc 2, from 11:56 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-21"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-22.mp4",
   "cat": "mamawedding",
   "emoji": "🌴",
   "title": "22. Arriving at the Hall",
   "caption": "Arriving at the wedding hall, jasmine and all. (Wedding disc 2, from 14:57 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-22"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-23.mp4",
   "cat": "mamawedding",
   "emoji": "🌸",
   "title": "23. The Welcome Party",
   "caption": "The ladies line up to welcome everyone at the hall. (Wedding disc 2, from 19:34 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-23"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-24.mp4",
   "cat": "mamawedding",
   "emoji": "✨",
   "title": "24. Dada's Title Portraits",
   "caption": "Dada in the classic wedding-video portrait frames. (Wedding disc 2, from 22:58 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-24"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-25.mp4",
   "cat": "mamawedding",
   "emoji": "🧺",
   "title": "25. Guests and Gift Trays",
   "caption": "The hall fills up, and the gift trays look splendid. (Wedding disc 2, from 27:31 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-25"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-26.mp4",
   "cat": "mamawedding",
   "emoji": "💐",
   "title": "26. Garlands at the Entrance",
   "caption": "Dada is welcomed with garlands. (Wedding disc 2, from 31:19 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-26"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-27.mp4",
   "cat": "mamawedding",
   "emoji": "🔥",
   "title": "27. The Rituals Begin",
   "caption": "The ceremony starts on the decorated stage. (Wedding disc 2, from 35:41 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-27"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-28.mp4",
   "cat": "mamawedding",
   "emoji": "📿",
   "title": "28. Prayers with the Priest",
   "caption": "The priest leads the prayers as the family watches. (Wedding disc 2, from 40:12 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-28"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-29.mp4",
   "cat": "mamawedding",
   "emoji": "💒",
   "title": "29. The Couple Takes Their Seats",
   "caption": "Dada and Mama are seated together for the rituals. (Wedding disc 2, from 43:29 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-29"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-30.mp4",
   "cat": "mamawedding",
   "emoji": "👀",
   "title": "30. All Eyes on the Stage",
   "caption": "The ceremony continues in front of a packed hall. (Wedding disc 2, from 47:40 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-30"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-31.mp4",
   "cat": "mamawedding",
   "emoji": "👪",
   "title": "31. Guests Watch On",
   "caption": "Relatives and friends look on as the rituals go on. (Wedding disc 2, from 51:56 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-31"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-32.mp4",
   "cat": "mamawedding",
   "emoji": "🌺",
   "title": "32. Blessings from the Ladies",
   "caption": "The ladies come up one by one to bless the couple. (Wedding disc 2, from 56:53 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-32"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-33.mp4",
   "cat": "mamawedding",
   "emoji": "🤲",
   "title": "33. Rituals with the Elders",
   "caption": "The elders join in on stage. (Wedding disc 2, from 61:26 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-33"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-34.mp4",
   "cat": "mamawedding",
   "emoji": "🌼",
   "title": "34. Garlanded and Blessed",
   "caption": "The newly-weds, garlanded, receive blessings. (Wedding disc 2, from 66:05 · about 2 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-34"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-35.mp4",
   "cat": "mamawedding",
   "emoji": "💛",
   "title": "35. More Blessings",
   "caption": "Blessing after blessing for the newly-weds. (Wedding disc 3, from 0:00 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-35"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-36.mp4",
   "cat": "mamawedding",
   "emoji": "✍️",
   "title": "36. Greetings After the Ceremony",
   "caption": "Greetings and a signing moment after the ceremony. (Wedding disc 3, from 3:28 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-36"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-37.mp4",
   "cat": "mamawedding",
   "emoji": "📷",
   "title": "37. Stage Photos with Family",
   "caption": "The family takes turns for photos on stage. (Wedding disc 3, from 6:53 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-37"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-38.mp4",
   "cat": "mamawedding",
   "emoji": "🥰",
   "title": "38. Relatives in the Hall",
   "caption": "Cheerful relatives and plenty of catching up. (Wedding disc 3, from 10:16 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-38"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-39.mp4",
   "cat": "mamawedding",
   "emoji": "🤗",
   "title": "39. Greeting the Guests",
   "caption": "The couple greets guests on stage. (Wedding disc 3, from 13:28 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-39"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-40.mp4",
   "cat": "mamawedding",
   "emoji": "🪧",
   "title": "40. “S. Subiah weds V. Smitha”",
   "caption": "The big banner, and more family photos. (Wedding disc 3, from 16:42 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-40"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-41.mp4",
   "cat": "mamawedding",
   "emoji": "🍛",
   "title": "41. The Wedding Feast",
   "caption": "The famous feast, served on banana leaves. (Wedding disc 3, from 20:10 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-41"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-42.mp4",
   "cat": "mamawedding",
   "emoji": "🎬",
   "title": "42. The Feast and “Our Wedding”",
   "caption": "More feast, then the “Our Wedding” title cards. (Wedding disc 3, from 23:33 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-42"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-43.mp4",
   "cat": "mamawedding",
   "emoji": "🏛️",
   "title": "43. The Reception Hall",
   "caption": "Flowers, then the reception hall itself. (Wedding disc 3, from 27:43 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-43"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-44.mp4",
   "cat": "mamawedding",
   "emoji": "🎊",
   "title": "44. Reception Photos",
   "caption": "Guests line up for photos with the couple. (Wedding disc 3, from 31:35 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-44"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-45.mp4",
   "cat": "mamawedding",
   "emoji": "🍽️",
   "title": "45. Dinner and Stage Photos",
   "caption": "Guests at dinner, and more photos on stage. (Wedding disc 3, from 36:31 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-45"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-46.mp4",
   "cat": "mamawedding",
   "emoji": "👋",
   "title": "46. Reception Greetings",
   "caption": "Handshakes, hugs and good wishes. (Wedding disc 3, from 41:09 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-46"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-47.mp4",
   "cat": "mamawedding",
   "emoji": "🌃",
   "title": "47. Evening Lights",
   "caption": "Evening lights and the couple on stage. (Wedding disc 3, from 44:16 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-47"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-48.mp4",
   "cat": "mamawedding",
   "emoji": "👨‍👩‍👧",
   "title": "48. Group Photos",
   "caption": "Group photo after group photo. (Wedding disc 3, from 47:28 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-48"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-49.mp4",
   "cat": "mamawedding",
   "emoji": "🧑‍🤝‍🧑",
   "title": "49. More Family Photos",
   "caption": "Every branch of the family gets its photo. (Wedding disc 3, from 51:43 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-49"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-50.mp4",
   "cat": "mamawedding",
   "emoji": "🎲",
   "title": "50. Fun Rituals with the Family",
   "caption": "Everyone crowds round for the playful rituals. (Wedding disc 3, from 55:08 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-50"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-51.mp4",
   "cat": "mamawedding",
   "emoji": "🌊",
   "title": "51. Final Rituals and a Seaside Montage",
   "caption": "The last rituals, then a seaside video montage. (Wedding disc 3, from 58:54 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-51"
  },
  {
   "kind": "video",
   "folder": "MamaWedding",
   "file": "Mama-Wedding-52.mp4",
   "cat": "mamawedding",
   "emoji": "🎇",
   "title": "52. Closing Titles",
   "caption": "The closing montage: long live the happy couple! (Wedding disc 3, from 63:22 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-wedding-52"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-01.mp4",
   "cat": "mamaceremony",
   "emoji": "🎬",
   "title": "1. Opening Titles",
   "caption": "The old tape begins with its title cards (from Nagercoil). Old VHS tape, so expect a few wobbly lines. (Ceremony tape 1, from 0:00 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-01"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-02.mp4",
   "cat": "mamaceremony",
   "emoji": "👨‍👩‍👧‍👦",
   "title": "2. The Family Gathers",
   "caption": "Family and little ones gather at the house. (Ceremony tape 1, from 3:22 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-02"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-03.mp4",
   "cat": "mamaceremony",
   "emoji": "🧒",
   "title": "3. Kids Everywhere",
   "caption": "Curious kids crowd in to see what's happening. (Ceremony tape 1, from 6:44 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-03"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-04.mp4",
   "cat": "mamaceremony",
   "emoji": "🌹",
   "title": "4. Flowers and First Blessings",
   "caption": "Rose-tinted titles, then the first blessings by the lamp. (Ceremony tape 1, from 10:56 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-04"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-05.mp4",
   "cat": "mamaceremony",
   "emoji": "💁‍♀️",
   "title": "5. Getting Ready with the Ladies",
   "caption": "The ladies help with the jewellery and flowers. (Ceremony tape 1, from 14:43 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-05"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-06.mp4",
   "cat": "mamaceremony",
   "emoji": "🥻",
   "title": "6. Dressing Up in Silk",
   "caption": "Silk saris, jasmine and a lot of fuss (the good kind). (Ceremony tape 1, from 18:01 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-06"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-07.mp4",
   "cat": "mamaceremony",
   "emoji": "🎎",
   "title": "7. Jewellery and the Doll Display",
   "caption": "Final touches, and a peek at the doll display. (Ceremony tape 1, from 21:15 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-07"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-08.mp4",
   "cat": "mamaceremony",
   "emoji": "💮",
   "title": "8. Flowers in the Hair",
   "caption": "Flowers pinned and jewellery on. (Ceremony tape 1, from 25:37 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-08"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-09.mp4",
   "cat": "mamaceremony",
   "emoji": "🚙",
   "title": "9. A Photo and the Family Car",
   "caption": "A photo moment, then the family car arrives. (Ceremony tape 1, from 30:16 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-09"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-10.mp4",
   "cat": "mamaceremony",
   "emoji": "🪑",
   "title": "10. Guests Gather",
   "caption": "Guests arrive and settle in. (Ceremony tape 1, from 33:22 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-10"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-11.mp4",
   "cat": "mamaceremony",
   "emoji": "👥",
   "title": "11. Guests Take Their Seats",
   "caption": "The chairs fill up. (Ceremony tape 1, from 37:01 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-11"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-12.mp4",
   "cat": "mamaceremony",
   "emoji": "🪔",
   "title": "12. The Lamp Is Lit",
   "caption": "The brass lamp glows as the ceremony begins. (Ceremony tape 1, from 40:16 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-12"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-13.mp4",
   "cat": "mamaceremony",
   "emoji": "🌸",
   "title": "13. Garlands and Blessings",
   "caption": "Garlanded in jasmine, with blessings all round. (Ceremony tape 1, from 44:56 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-13"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-14.mp4",
   "cat": "mamaceremony",
   "emoji": "🙌",
   "title": "14. Blessings from the Elders",
   "caption": "The elders come forward one by one. (Ceremony tape 1, from 49:44 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-14"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-15.mp4",
   "cat": "mamaceremony",
   "emoji": "🕯️",
   "title": "15. By the Lamp",
   "caption": "The ceremony continues by the lamp. (Ceremony tape 1, from 54:22 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-15"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-16.mp4",
   "cat": "mamaceremony",
   "emoji": "📼",
   "title": "16. The Second Tape Begins",
   "caption": "A new tape starts and the ceremony carries on. (Ceremony tape 2, from 0:00 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-16"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-17.mp4",
   "cat": "mamaceremony",
   "emoji": "😊",
   "title": "17. Smiles and Blessings",
   "caption": "Happy faces and more blessings. (Ceremony tape 2, from 4:20 · about 3 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-17"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-18.mp4",
   "cat": "mamaceremony",
   "emoji": "🍛",
   "title": "18. The Feast Begins",
   "caption": "Everyone sits down to eat. (Ceremony tape 2, from 7:43 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-18"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-19.mp4",
   "cat": "mamaceremony",
   "emoji": "🍃",
   "title": "19. Feast on Banana Leaves",
   "caption": "A proper feast, served on banana leaves. (Ceremony tape 2, from 11:36 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-19"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-20.mp4",
   "cat": "mamaceremony",
   "emoji": "💃",
   "title": "20. Dance Time",
   "caption": "A little dancer takes the stage. (Ceremony tape 2, from 15:12 · about 5 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-20"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-21.mp4",
   "cat": "mamaceremony",
   "emoji": "🎭",
   "title": "21. Little Performers",
   "caption": "More performances from the little ones. (Ceremony tape 2, from 20:07 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-21"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-22.mp4",
   "cat": "mamaceremony",
   "emoji": "🎶",
   "title": "22. More Performances",
   "caption": "The show goes on. (Ceremony tape 2, from 24:21 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-22"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-23.mp4",
   "cat": "mamaceremony",
   "emoji": "📸",
   "title": "23. Family Photos Outside",
   "caption": "Family photos outside, elders and all. (Ceremony tape 2, from 28:34 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-23"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-24.mp4",
   "cat": "mamaceremony",
   "emoji": "✨",
   "title": "24. Video Effects and Outdoors",
   "caption": "Classic video effects, then outdoor scenes. (Ceremony tape 2, from 32:39 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-24"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-25.mp4",
   "cat": "mamaceremony",
   "emoji": "🧡",
   "title": "25. A Little Dancer at Home",
   "caption": "A tiny dancer in orange shows her moves. (Ceremony tape 2, from 36:10 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-25"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-26.mp4",
   "cat": "mamaceremony",
   "emoji": "👶",
   "title": "26. Family and Little Ones",
   "caption": "Cuddles with the little ones. (Ceremony tape 2, from 39:58 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-26"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-27.mp4",
   "cat": "mamaceremony",
   "emoji": "🏠",
   "title": "27. At Home with the Family",
   "caption": "Everyday moments at home, kitchen included. (Ceremony tape 2, from 43:54 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-27"
  },
  {
   "kind": "video",
   "folder": "MamaCeremony",
   "file": "Mama-Ceremony-28.mp4",
   "cat": "mamaceremony",
   "emoji": "🎞️",
   "title": "28. The Last Moments on Tape",
   "caption": "The tape's final moments. (Ceremony tape 2, from 47:28 · about 4 min.)",
   "added": "2026-09-16",
   "slug": "mama-ceremony-28"
  },
  {
   "kind": "image",
   "folder": "Keepsakes",
   "file": "Drawing-2021.png",
   "cat": "keepsakes",
   "emoji": "🎨",
   "title": "A Room in Ink (2021)",
   "caption": "Her pen-and-wash drawing of a bedroom: the bed under the window, a clock on the wall, a shelf of little treasures, a teddy in the cupboard and a map by the door. Tap the picture to zoom in.",
   "added": "2026-09-25",
   "slug": "a-room-in-ink-2021",
   "when": "2021"
  },
  {
   "kind": "image",
   "folder": "Keepsakes",
   "file": "Rabbit-Pros-and-Cons.jpg",
   "cat": "keepsakes",
   "emoji": "🐰",
   "title": "Why We Should Get a Rabbit",
   "caption": "Her case for a rabbit, in her own handwriting: pros on the left, cons on the right, and tips along the bottom. Note the other pet crossed out in the title. Tap the picture to zoom in.",
   "added": "2026-09-24",
   "slug": "why-we-should-get-a-rabbit"
  },
  {
   "kind": "image",
   "folder": "Keepsakes",
   "file": "Santa-2009.jpg",
   "cat": "keepsakes",
   "emoji": "🎅",
   "title": "With Santa, 2009",
   "caption": "One very small girl, one very large beard. The camera recorded 7 November 2009.",
   "added": "2026-09-24",
   "slug": "with-santa-2009",
   "when": "7 November 2009"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-01.jpg",
   "cat": "art",
   "emoji": "✏️",
   "title": "Line Art: A Calm Face",
   "caption": "Clean line work: a calm face with a beaded collar, drawn straight onto the iPad. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "line-art-a-calm-face"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-02.jpg",
   "cat": "art",
   "emoji": "💜",
   "title": "Violet Warrior",
   "caption": "A tall figure in spiked violet armour, all sharp angles and long claws. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "violet-warrior"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-03.jpg",
   "cat": "art",
   "emoji": "🗓️",
   "title": "Violet Warrior · 29 Days Left",
   "caption": "The same warrior, with “29 DAYS LEFT!” written in the corner — part of a drawing challenge. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "violet-warrior-29-days-left"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-04.jpg",
   "cat": "art",
   "emoji": "🕷️",
   "title": "Spider in Blue",
   "caption": "A spider on a glowing blue web, with comic-book dots behind it. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "spider-in-blue"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-05.jpg",
   "cat": "art",
   "emoji": "📓",
   "title": "Pencil Study",
   "caption": "A sketchbook page: a figure in profile, framed like a portrait. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "pencil-study"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-06.jpg",
   "cat": "art",
   "emoji": "🍂",
   "title": "Day 30",
   "caption": "A redhead in a high ponytail with a very serious stare. Marked “DAY 30”. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "day-30"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-07.jpg",
   "cat": "art",
   "emoji": "💧",
   "title": "Two Water Creatures",
   "caption": "Two blue-and-teal creatures mid-pose, ready for a fight. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "two-water-creatures"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-08.jpg",
   "cat": "art",
   "emoji": "🐲",
   "title": "Three Dragons",
   "caption": "Spiky dragon heads in cream and sea green, one with a gaping grin. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "three-dragons"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-09.jpg",
   "cat": "art",
   "emoji": "✏️",
   "title": "Dragon in the Sketchbook",
   "caption": "A dragon's head worked out in pencil and red pen on spiral paper. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "dragon-in-the-sketchbook"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-10.jpg",
   "cat": "art",
   "emoji": "😄",
   "title": "“Great Expectations Is Mid at Best”",
   "caption": "A pencil drawing with her own verdict written into the picture. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "great-expectations-is-mid-at-best"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-11.jpg",
   "cat": "art",
   "emoji": "⚡",
   "title": "Storm Serpent",
   "caption": "A pink-and-violet sea dragon rising through lightning and dark water. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "storm-serpent"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-12.jpg",
   "cat": "art",
   "emoji": "❄️",
   "title": "Two Dragons Talking",
   "caption": "A sand-coloured dragon and a frosty blue one mid-conversation, snowflakes and all. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "two-dragons-talking"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-13.jpg",
   "cat": "art",
   "emoji": "🌊",
   "title": "Under the Water",
   "caption": "A long green dragon gliding through sunlit shallows, with little fish for company. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "under-the-water"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-14.jpg",
   "cat": "art",
   "emoji": "🐉",
   "title": "Blue Dragon",
   "caption": "A deep-blue dragon in profile, with “BALEEN!” written beside it. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "blue-dragon"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-15.jpg",
   "cat": "art",
   "emoji": "👑",
   "title": "Gold Dragon",
   "caption": "A golden dragon with a braided mane, one long horn and a glowing eye. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "gold-dragon"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-16.jpg",
   "cat": "art",
   "emoji": "🎃",
   "title": "Pumpkin Pie Cookie",
   "caption": "A little character in a pumpkin dress, labelled in her own handwriting. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "pumpkin-pie-cookie"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-17.jpg",
   "cat": "art",
   "emoji": "🍷",
   "title": "Portrait with a Glass",
   "caption": "A girl with long brown hair raising a glass, in soft purples. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "portrait-with-a-glass"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-18.jpg",
   "cat": "art",
   "emoji": "🎭",
   "title": "The Green Apron",
   "caption": "A figure in goggles and a mask, wrapped in smoke. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "the-green-apron"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-19.jpg",
   "cat": "art",
   "emoji": "⭐",
   "title": "Girl with Twin Buns",
   "caption": "A bright, starry portrait: long blonde hair and a very cheerful face. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "girl-with-twin-buns"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-20.jpg",
   "cat": "art",
   "emoji": "🔥",
   "title": "Flame Girl",
   "caption": "An orange-haired character with flame markings, drawn sticker-style with a white outline. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "flame-girl"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-21.jpg",
   "cat": "art",
   "emoji": "💃",
   "title": "Dancer in Violet",
   "caption": "A full-length character design: braids, gold jewellery and flowing trousers. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "dancer-in-violet"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-22.jpg",
   "cat": "art",
   "emoji": "😆",
   "title": "“Stupid” and the Sane One",
   "caption": "Two characters, with her own labels: one “Stupid”, the other “supposed to be the sane person, but is also stupid”. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "stupid-and-the-sane-one"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-23.jpg",
   "cat": "art",
   "emoji": "✏️",
   "title": "Sketchbook Faces",
   "caption": "A page of pencil faces: profiles, eyes, and several tries at the same head. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "sketchbook-faces"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-24.jpg",
   "cat": "art",
   "emoji": "🦖",
   "title": "Dinosaur Study",
   "caption": "A painted study of a big reptilian skull, all teeth and shadow. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "dinosaur-study"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-25.jpg",
   "cat": "art",
   "emoji": "🌸",
   "title": "Pink and Mint Creature",
   "caption": "A round creature in purple and mint, with a little crown and a lot of attitude. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "pink-and-mint-creature"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-26.jpg",
   "cat": "art",
   "emoji": "💙",
   "title": "Yoko Onigi",
   "caption": "A blue-haired portrait, titled on the page, photographed from the screen. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "yoko-onigi"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-27.jpg",
   "cat": "art",
   "emoji": "☁️",
   "title": "Sky Creature",
   "caption": "A golden, many-finned creature drifting through big white clouds. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "sky-creature"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-28.jpg",
   "cat": "art",
   "emoji": "🗑️",
   "title": "In the Bin",
   "caption": "A pen drawing: an armoured character sitting glumly in a rubbish bin. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "in-the-bin"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-29.jpg",
   "cat": "art",
   "emoji": "⚡",
   "title": "Sparks Flying",
   "caption": "A cheerful orange creature with lightning-bolt ears on a soft green background. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "sparks-flying"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-30.jpg",
   "cat": "art",
   "emoji": "🌼",
   "title": "Blossom and Lightning",
   "caption": "A golden-haired figure with purple blossoms and a crackle of light across one eye. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "blossom-and-lightning"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-31.jpg",
   "cat": "art",
   "emoji": "🌀",
   "title": "Portrait in Blue",
   "caption": "A close-up portrait with looped hair, freckles and swirls in the background. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "portrait-in-blue"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-32.jpg",
   "cat": "art",
   "emoji": "🧔",
   "title": "Half and Half",
   "caption": "A bearded portrait, split down the middle into warm and cool halves. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "half-and-half"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-33.jpg",
   "cat": "art",
   "emoji": "🌿",
   "title": "Green-Eyed Portrait",
   "caption": "A portrait in a headband and green tunic, signed in gold. Tap the picture to open it big.",
   "added": "2026-09-25",
   "slug": "green-eyed-portrait"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-34.jpg",
   "cat": "art",
   "emoji": "🐯",
   "title": "Tiger, Mid-Roar",
   "caption": "A painted big cat's head caught mid-roar, on a starry blue background. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "tiger-mid-roar"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-35.jpg",
   "cat": "art",
   "emoji": "❄️",
   "title": "Ice-Blue Curls",
   "caption": "A portrait with pale blue ringlets and a little winged-heart hairpin. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "ice-blue-curls"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-36.jpg",
   "cat": "art",
   "emoji": "🌊",
   "title": "Hurricane",
   "caption": "A green sea dragon, labelled in her hand: “HURRICANE! Sea/Rain”. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "hurricane"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-37.jpg",
   "cat": "art",
   "emoji": "🍂",
   "title": "Leafeon",
   "caption": "A leafy creature mid-step on dotted white paper, labelled “LEAFEON”. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "leafeon"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-38.jpg",
   "cat": "art",
   "emoji": "🎀",
   "title": "Pink and Black",
   "caption": "A sticker-style character with a big black bow and bright red eyes. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "pink-and-black"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-39.jpg",
   "cat": "art",
   "emoji": "🌿",
   "title": "Little Green Cat",
   "caption": "A fluffy green cat with pink eyes and a star over its shoulder. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "little-green-cat"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-40.jpg",
   "cat": "art",
   "emoji": "📝",
   "title": "Yangchen and Kavik",
   "caption": "A lined-paper doodle of two characters, both named in her handwriting. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "yangchen-and-kavik"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-41.jpg",
   "cat": "art",
   "emoji": "🧢",
   "title": "Annabeth",
   "caption": "A full-length character design in baggy jeans, labelled “ANNABETH”. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "annabeth"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-42.jpg",
   "cat": "art",
   "emoji": "🐲",
   "title": "Blue Dragon, Twice",
   "caption": "A painted blue dragon head, with the pencil version beside it. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "blue-dragon-twice"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-43.jpg",
   "cat": "art",
   "emoji": "🖤",
   "title": "Big Eyes",
   "caption": "A glossy black dragon head with enormous green eyes. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "big-eyes"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-44.jpg",
   "cat": "art",
   "emoji": "💨",
   "title": "Yangchen (Study)",
   "caption": "Her painted portrait beside the picture she was working from. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "yangchen-study"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-45.jpg",
   "cat": "art",
   "emoji": "✏️",
   "title": "Miss Queen",
   "caption": "A pencil portrait on lined paper, titled “YANGCHEN ML ♥”. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "miss-queen"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-46.jpg",
   "cat": "art",
   "emoji": "💜",
   "title": "Purple Dragon, Sketch to Colour",
   "caption": "A purple dragon in colour, with its line-art version pinned beside it. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "purple-dragon-sketch-to-colour"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-47.jpg",
   "cat": "art",
   "emoji": "😄",
   "title": "Yellow Ponytail",
   "caption": "A grinning portrait with glasses, gold armbands and plenty of cheek. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "yellow-ponytail"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-48.jpg",
   "cat": "art",
   "emoji": "🌀",
   "title": "Aang",
   "caption": "Two poses of the same character with “AANG” written big, fans and air swirls. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "aang"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-49.jpg",
   "cat": "art",
   "emoji": "🟠",
   "title": "Yangchen!",
   "caption": "A smiling portrait in orange robes with prayer beads, titled in her hand. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "yangchen"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-50.jpg",
   "cat": "art",
   "emoji": "👋",
   "title": "Waving Hello",
   "caption": "A friendly character with braids and a blue tunic, mid-wave. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "waving-hello"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-51.jpg",
   "cat": "art",
   "emoji": "🔥",
   "title": "Zuko",
   "caption": "A dark-haired portrait with a scarred eye and red collar, labelled “ZUKO!”. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "zuko"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-52.jpg",
   "cat": "art",
   "emoji": "🧛",
   "title": "Pigtails and Fangs",
   "caption": "A pale character with long black-and-pink pigtails and little fangs. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "pigtails-and-fangs"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-53.jpg",
   "cat": "art",
   "emoji": "💖",
   "title": "Two Dragons, Nose to Nose",
   "caption": "An orange dragon and a pink one leaning together, both named in her hand. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "two-dragons-nose-to-nose"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-54.jpg",
   "cat": "art",
   "emoji": "🐺",
   "title": "Naga",
   "caption": "Three studies of a big white beast, titled “naga”. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "naga"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-55.jpg",
   "cat": "art",
   "emoji": "🦄",
   "title": "Purple Unicorn",
   "caption": "A pony-style unicorn with a striped mane and tail. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "purple-unicorn"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-56.jpg",
   "cat": "art",
   "emoji": "🐉",
   "title": "The Hideous Zippleback",
   "caption": "A two-headed green dragon, titled in her own lettering. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "the-hideous-zippleback"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-57.jpg",
   "cat": "art",
   "emoji": "🐑",
   "title": "Red",
   "caption": "A lamb standing alone in the dark, with “RED” just visible behind it. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "red"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-58.jpg",
   "cat": "art",
   "emoji": "💚",
   "title": "Kyoshi",
   "caption": "A portrait in war paint, headdress and green robes, labelled “Kyoshi”. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "kyoshi"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-59.jpg",
   "cat": "art",
   "emoji": "🌬️",
   "title": "Green Dragon in the Wind",
   "caption": "A leafy green dragon among swirls and falling petals. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "green-dragon-in-the-wind"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-60.jpg",
   "cat": "art",
   "emoji": "🤸",
   "title": "Ty Lee",
   "caption": "A character mid-kick with a long braid flying, labelled “TY LEE!”. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "ty-lee"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-61.jpg",
   "cat": "art",
   "emoji": "🌅",
   "title": "Dragon at Sunset",
   "caption": "A tiny flier crossing a huge pink-and-gold evening sky. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "dragon-at-sunset"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-62.jpg",
   "cat": "art",
   "emoji": "🌈",
   "title": "Rainbow Wings",
   "caption": "A teal-and-orange dragon gliding over rolling green hills. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "rainbow-wings"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-63.jpg",
   "cat": "art",
   "emoji": "🦁",
   "title": "Vinnie",
   "caption": "A character with a wild golden mane, labelled “VINNIE!”. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "vinnie"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-64.jpg",
   "cat": "art",
   "emoji": "🐍",
   "title": "Two Heads, One Dragon",
   "caption": "A green twin-headed dragon in flight, grinning on both ends. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "two-heads-one-dragon"
  },
  {
   "kind": "image",
   "folder": "Art",
   "file": "Art-65.jpg",
   "cat": "art",
   "emoji": "💙",
   "title": "Blue Pigtails, Mid-Leap",
   "caption": "A sticker-style character caught mid-jump, arms out and hair flying. Tap the picture to open it big.",
   "added": "2026-09-26",
   "slug": "blue-pigtails-mid-leap"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "3rd Birthday Party - Game 1 [GeZKe47ylH8].mp4",
   "cat": "birthday",
   "emoji": "🎉",
   "title": "3rd Birthday: Party Game 1",
   "caption": "Let the party games begin!",
   "added": "2026-09-15",
   "slug": "3rd-birthday-party-game-1"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "3rd Birthday Party - Game 2 [fjwC7lYGOzg].mp4",
   "cat": "birthday",
   "emoji": "🎲",
   "title": "3rd Birthday: Party Game 2",
   "caption": "Party game number two. Let the games continue!",
   "added": "2026-09-15",
   "slug": "3rd-birthday-party-game-2"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "3rd Birthday Party - PinTheTail [mCPJR8Kki9Q].mp4",
   "cat": "birthday",
   "emoji": "🫏",
   "title": "3rd Birthday: Pin the Tail",
   "caption": "Blindfold on… where does that tail go?!",
   "added": "2026-09-15",
   "slug": "3rd-birthday-pin-the-tail"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "3rd Birthday Present 1 [EzhM0WE2WPE].mp4",
   "cat": "birthday",
   "emoji": "🎁",
   "title": "3rd Birthday: Present #1",
   "caption": "What's inside? Present number one!",
   "added": "2026-09-15",
   "slug": "3rd-birthday-present-1"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "3rd Birthday Present 2 [x2z-7EpwUXg].mp4",
   "cat": "birthday",
   "emoji": "🎀",
   "title": "3rd Birthday: Present #2",
   "caption": "Rip! Present number two.",
   "added": "2026-09-15",
   "slug": "3rd-birthday-present-2"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "3rd Birthday Party - Cake [qdyYNdaoYuo].mp4",
   "cat": "birthday",
   "emoji": "🍰",
   "title": "3rd Birthday: The Cake",
   "caption": "Candles lit, song sung. It's cake time!",
   "added": "2026-09-15",
   "slug": "3rd-birthday-the-cake"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "3rd Birthday Party - Pinata [0UhuX0JFavE].mp4",
   "cat": "birthday",
   "emoji": "🪅",
   "title": "3rd Birthday: The Piñata",
   "caption": "Whack! Whack! 3rd birthday piñata action.",
   "added": "2026-09-15",
   "slug": "3rd-birthday-the-pi-ata"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Birthday @School [cHVYA2vcIlY].mp4",
   "cat": "birthday",
   "emoji": "🏫",
   "title": "Birthday at School",
   "caption": "Celebrating the birthday with the school crew.",
   "added": "2026-09-15",
   "slug": "birthday-at-school"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Birthday Morning 1 [IRa4pck6bSo].mp4",
   "cat": "birthday",
   "emoji": "🌅",
   "title": "Birthday Morning (Part 1)",
   "caption": "Wakey wakey, birthday girl! The birthday morning begins.",
   "added": "2026-09-15",
   "slug": "birthday-morning-part-1"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Birthday Morning 2 [pU2ttNtoYbg].mp4",
   "cat": "birthday",
   "emoji": "🎁",
   "title": "Birthday Morning (Part 2)",
   "caption": "The birthday morning continues…",
   "added": "2026-09-15",
   "slug": "birthday-morning-part-2"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Birthday Morning 3 [1daXVvwjYnw].mp4",
   "cat": "birthday",
   "emoji": "🥳",
   "title": "Birthday Morning (Part 3)",
   "caption": "Birthday morning, the grand finale.",
   "added": "2026-09-15",
   "slug": "birthday-morning-part-3"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "First Birthday Party [ZA7NZ5kfKVs].mp4",
   "cat": "birthday",
   "emoji": "1️⃣",
   "title": "First Birthday Party",
   "caption": "ONE! The very first birthday party.",
   "added": "2026-09-15",
   "slug": "first-birthday-party"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Second Birthday Party [JDY7JWtumpE].mp4",
   "cat": "birthday",
   "emoji": "2️⃣",
   "title": "Second Birthday Party",
   "caption": "TWO! The second birthday party.",
   "added": "2026-09-15",
   "slug": "second-birthday-party"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Chat About Easter Show [gP7jIsAOTag].mp4",
   "cat": "easter",
   "emoji": "🎪",
   "title": "Chatting About the Easter Show",
   "caption": "The full debrief on the Easter Show, straight from the source.",
   "added": "2026-09-15",
   "slug": "chatting-about-the-easter-show"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Easter 2012 Egg Hunt Surprise [0IZuo-bFFbI].mp4",
   "cat": "easter",
   "emoji": "🤩",
   "title": "Easter 2012: Egg Hunt Surprise",
   "caption": "An egg hunt… with a surprise!",
   "added": "2026-09-15",
   "slug": "easter-2012-egg-hunt-surprise",
   "when": "2012"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Easter 2012 Happy Easter [9oOWFmMsa1M].mp4",
   "cat": "easter",
   "emoji": "🐰",
   "title": "Easter 2012: Happy Easter!",
   "caption": "A very important Easter message. Happy Easter!",
   "added": "2026-09-15",
   "slug": "easter-2012-happy-easter",
   "when": "2012"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Easter 2012  Egg Hunt [4F-o4aQarxE].mp4",
   "cat": "easter",
   "emoji": "🧺",
   "title": "Easter 2012: The Egg Hunt",
   "caption": "Basket ready… the 2012 Easter egg hunt is ON!",
   "added": "2026-09-15",
   "slug": "easter-2012-the-egg-hunt",
   "when": "2012"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Easter 2012 Yumm Yumm [zvqmezdnu7o].mp4",
   "cat": "easter",
   "emoji": "🍫",
   "title": "Easter 2012: Yumm Yumm",
   "caption": "Chocolate verdict: yumm yumm.",
   "added": "2026-09-15",
   "slug": "easter-2012-yumm-yumm",
   "when": "2012"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Easter Egg Painting at Mall [U8fzMJwA6F0].mp4",
   "cat": "easter",
   "emoji": "🥚",
   "title": "Easter Egg Painting at the Mall",
   "caption": "Brush in hand, egg in the other: Easter egg painting at the mall.",
   "added": "2026-09-15",
   "slug": "easter-egg-painting-at-the-mall"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Facepainting at Whitcoulls Easter Fun... [Cy5m7m30M5U].mp4",
   "cat": "easter",
   "emoji": "🎨",
   "title": "Face Painting at Whitcoulls Easter Fun",
   "caption": "Sit still… almost… the Easter face-painting masterpiece.",
   "added": "2026-09-15",
   "slug": "face-painting-at-whitcoulls-easter-fun"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Royal Easter Show 2012. Bouncy Slide. [AO2ovwEZIdI].mp4",
   "cat": "easter",
   "emoji": "🛝",
   "title": "Royal Easter Show 2012: Bouncy Slide",
   "caption": "Weeee! The bouncy slide at the 2012 Royal Easter Show.",
   "added": "2026-09-15",
   "slug": "royal-easter-show-2012-bouncy-slide",
   "when": "2012"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Royal Easter Show 2012. Carousal. [-lvre7J5GbQ].mp4",
   "cat": "easter",
   "emoji": "🎠",
   "title": "Royal Easter Show 2012: Carousel",
   "caption": "Round and round on the carousel at the 2012 Royal Easter Show.",
   "added": "2026-09-15",
   "slug": "royal-easter-show-2012-carousel",
   "when": "2012"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "At Zoo [6hS3YSJlfME].mp4",
   "cat": "zoo",
   "emoji": "🦒",
   "title": "A Day at the Zoo",
   "caption": "Hello, animals! A day out at the zoo.",
   "added": "2026-09-15",
   "slug": "a-day-at-the-zoo"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Bike Riding - Day 2 [Xiy43tjJku8].mp4",
   "cat": "zoo",
   "emoji": "🚲",
   "title": "Bike Riding: Day 2",
   "caption": "Day two on the bike, and getting the hang of it!",
   "added": "2026-09-15",
   "slug": "bike-riding-day-2"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Bouncy Slide [md3WjmOB7SE].mp4",
   "cat": "zoo",
   "emoji": "🎈",
   "title": "Bouncy Slide",
   "caption": "Bounce, slide, repeat!",
   "added": "2026-09-15",
   "slug": "bouncy-slide"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Carousel @ Devonport Ferry Terminal [3cVF4BEZxnU].mp4",
   "cat": "zoo",
   "emoji": "🎡",
   "title": "Carousel at Devonport Ferry Terminal",
   "caption": "A spin on the carousel at Devonport Ferry Terminal.",
   "added": "2026-09-15",
   "slug": "carousel-at-devonport-ferry-terminal"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Climbing @ Western Springs Playground [T8tkHKaDY3A].mp4",
   "cat": "zoo",
   "emoji": "🧗",
   "title": "Climbing at Western Springs",
   "caption": "Up, up, up at Western Springs Playground.",
   "added": "2026-09-15",
   "slug": "climbing-at-western-springs"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Computer Work At Zoo [S_Zqz0EzHuI].mp4",
   "cat": "zoo",
   "emoji": "💻",
   "title": "Computer Work at the Zoo",
   "caption": "Very important computer work… at the zoo.",
   "added": "2026-09-15",
   "slug": "computer-work-at-the-zoo"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Mountain Climbing [BfisxBF5JBQ].mp4",
   "cat": "zoo",
   "emoji": "⛰️",
   "title": "Mountain Climbing",
   "caption": "Onwards and upwards: the great mountain climb!",
   "added": "2026-09-15",
   "slug": "mountain-climbing"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Rock Climbing At Zoo [OAzQ9nM9G3s].mp4",
   "cat": "zoo",
   "emoji": "🧗‍♀️",
   "title": "Rock Climbing at the Zoo",
   "caption": "Tiny climber, big wall. Rock climbing at the zoo!",
   "added": "2026-09-15",
   "slug": "rock-climbing-at-the-zoo"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Rope Walking At Zoo [CaWXoGB_F_I].mp4",
   "cat": "zoo",
   "emoji": "🪢",
   "title": "Rope Walking at the Zoo",
   "caption": "Steady… steady… rope walking at the zoo.",
   "added": "2026-09-15",
   "slug": "rope-walking-at-the-zoo"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Riding Scooter on 9th Apr [JRXcqdUDWKo].mp4",
   "cat": "zoo",
   "emoji": "🛴",
   "title": "Scooter Ride (9 April)",
   "caption": "Whoosh! Scooter riding on the 9th of April.",
   "added": "2026-09-15",
   "slug": "scooter-ride-9-april"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "@SnowPlanet [WBnYD_zT9U4].mp4",
   "cat": "zoo",
   "emoji": "❄️",
   "title": "Snow Planet (Part 1)",
   "caption": "Brrr! A trip to Snow Planet. Snow, cold cheeks and big smiles.",
   "added": "2026-09-15",
   "slug": "snow-planet-part-1"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "@SnowPlanet [RZY8J3cV6RM].mp4",
   "cat": "zoo",
   "emoji": "⛄",
   "title": "Snow Planet (Part 2)",
   "caption": "More snowy fun at Snow Planet. Round two!",
   "added": "2026-09-15",
   "slug": "snow-planet-part-2"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Swinging @ Western Springs Playground [ewA-mgJ2-Gs].mp4",
   "cat": "zoo",
   "emoji": "🌳",
   "title": "Swinging at Western Springs",
   "caption": "Higher! Higher! Swinging at Western Springs Playground.",
   "added": "2026-09-15",
   "slug": "swinging-at-western-springs"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Riding New Bike on 9th Apr [JRFfkWrAsi4].mp4",
   "cat": "zoo",
   "emoji": "🚴‍♀️",
   "title": "The New Bike (9 April)",
   "caption": "Shiny new bike, first rides, 9th of April.",
   "added": "2026-09-15",
   "slug": "the-new-bike-9-april"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "At Playgroup 2 [LEBwZ1VuALc].mp4",
   "cat": "school",
   "emoji": "🧸",
   "title": "At Playgroup (Part 2)",
   "caption": "Another busy morning at playgroup.",
   "added": "2026-09-15",
   "slug": "at-playgroup-part-2"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "@ School with Jeeta Teacher [v_4YoLTnGMI].mp4",
   "cat": "school",
   "emoji": "👩‍🏫",
   "title": "At School with Jeeta Teacher",
   "caption": "School time with Jeeta Teacher.",
   "added": "2026-09-15",
   "slug": "at-school-with-jeeta-teacher"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Balancing Bridge @ Playschool [mIW_YCu493Q].mp4",
   "cat": "school",
   "emoji": "🌉",
   "title": "Balancing Bridge at Playschool",
   "caption": "Arms out, eyes forward: the playschool balancing bridge.",
   "added": "2026-09-15",
   "slug": "balancing-bridge-at-playschool"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Dance Class Last Day of the Term Certificate [yJvhpjwmGD4].mp4",
   "cat": "school",
   "emoji": "🏅",
   "title": "Dance Class: Certificate Time",
   "caption": "Last day of term, and a certificate for our little dancer!",
   "added": "2026-09-15",
   "slug": "dance-class-certificate-time"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Dance Class Last Day of the Term [lBR1HOPllfE].mp4",
   "cat": "school",
   "emoji": "💃",
   "title": "Dance Class: Last Day of Term",
   "caption": "Showtime! Dance moves from the last day of term.",
   "added": "2026-09-15",
   "slug": "dance-class-last-day-of-term"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Playgroup 1 [IkY7rubKzf4].mp4",
   "cat": "school",
   "emoji": "🧩",
   "title": "Playgroup (Part 1)",
   "caption": "Playgroup, episode one.",
   "added": "2026-09-15",
   "slug": "playgroup-part-1"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Playgroup 2 [vXRJ6huTjfM].mp4",
   "cat": "school",
   "emoji": "🪀",
   "title": "Playgroup (Part 2)",
   "caption": "Playgroup, episode two.",
   "added": "2026-09-15",
   "slug": "playgroup-part-2"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Playgroup 3 [RqkY9xmJZv0].mp4",
   "cat": "school",
   "emoji": "🖍️",
   "title": "Playgroup (Part 3)",
   "caption": "Playgroup, episode three.",
   "added": "2026-09-15",
   "slug": "playgroup-part-3"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Washing Hands @ Playschool with new friend [2T0iEKyNzUU].mp4",
   "cat": "school",
   "emoji": "🧼",
   "title": "Washing Hands with a New Friend",
   "caption": "Scrub-a-dub at playschool, with a brand-new friend.",
   "added": "2026-09-15",
   "slug": "washing-hands-with-a-new-friend"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Animals [AqbSkbdxZic].mp4",
   "cat": "songs",
   "emoji": "🐘",
   "title": "Animals",
   "caption": "Roar! Moo! Quack! All about the animals.",
   "added": "2026-09-15",
   "slug": "animals"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Anthakshari [z_ljBbm_HWs].mp4",
   "cat": "songs",
   "emoji": "🎤",
   "title": "Anthakshari",
   "caption": "Antakshari! The song-chain game, family edition.",
   "added": "2026-09-15",
   "slug": "anthakshari"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "I Love Barney!!! [d5VRxssYQno].mp4",
   "cat": "songs",
   "emoji": "🦖",
   "title": "I Love Barney!!!",
   "caption": "Three exclamation marks' worth of Barney love.",
   "added": "2026-09-15",
   "slug": "i-love-barney"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Incy Wincy Spider Song [d8nUkcreXb8].mp4",
   "cat": "songs",
   "emoji": "🕷️",
   "title": "Incy Wincy Spider",
   "caption": "Up the water spout… with all the actions!",
   "added": "2026-09-15",
   "slug": "incy-wincy-spider"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Kural [jHKqDWkEsz8].mp4",
   "cat": "songs",
   "emoji": "📜",
   "title": "Kural Time",
   "caption": "Kural time. Listen closely!",
   "added": "2026-09-15",
   "slug": "kural-time"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Reading ＂Just Like My Dad＂ (her next favorite) book with Mama [awA6Eh5ovto].mp4",
   "cat": "songs",
   "emoji": "📖",
   "title": "Reading “Just Like My Dad” with Mama",
   "caption": "Storytime with Mama and her next-favourite book, “Just Like My Dad”.",
   "added": "2026-09-15",
   "slug": "reading-just-like-my-dad-with-mama"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Reading ＂Just Like My Mum＂ (her favorite) book on her own [AZYlNfo-5YI].mp4",
   "cat": "songs",
   "emoji": "📚",
   "title": "Reading “Just Like My Mum” All By Herself",
   "caption": "Her favourite book, “Just Like My Mum”, read ALL by herself!",
   "added": "2026-09-15",
   "slug": "reading-just-like-my-mum-all-by-herself"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Reading ＂Just Like My Mum＂ (her favorite) book with Mama [_a8e4uIzs1c].mp4",
   "cat": "songs",
   "emoji": "📕",
   "title": "Reading “Just Like My Mum” with Mama",
   "caption": "Her all-time favourite, “Just Like My Mum”, read together with Mama.",
   "added": "2026-09-15",
   "slug": "reading-just-like-my-mum-with-mama"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Rhymes [YNzOhnb8fqM].mp4",
   "cat": "songs",
   "emoji": "🎶",
   "title": "Rhymes",
   "caption": "A rhyme-time medley.",
   "added": "2026-09-15",
   "slug": "rhymes"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "ABC Song [DbWMKEAFLJ8].mp4",
   "cat": "songs",
   "emoji": "🔤",
   "title": "The ABC Song",
   "caption": "A-B-C-D… now we know our ABCs!",
   "added": "2026-09-15",
   "slug": "the-abc-song"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "I Love You Song [-96b9X603VM].mp4",
   "cat": "songs",
   "emoji": "💗",
   "title": "The I Love You Song",
   "caption": "A song with the best lyrics ever written. Warning: may cause happy tears.",
   "added": "2026-09-15",
   "slug": "the-i-love-you-song"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Keyboard Player [lC9Vg674vOg].mp4",
   "cat": "songs",
   "emoji": "🎹",
   "title": "The Keyboard Player",
   "caption": "Ladies and gentlemen… on the keyboard…",
   "added": "2026-09-15",
   "slug": "the-keyboard-player"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Chat @ Home [Fr3hZFaFpQc].mp4",
   "cat": "home",
   "emoji": "☕",
   "title": "A Chat at Home",
   "caption": "Settle in for a little chat at home.",
   "added": "2026-09-15",
   "slug": "a-chat-at-home"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Adam with Kalla Alugai [iYc8lygpKgo].mp4",
   "cat": "home",
   "emoji": "😭",
   "title": "Adam and the Kalla Alugai",
   "caption": "Adam, plus a performance of kalla alugai (the famous pretend cry). Award-worthy.",
   "added": "2026-09-15",
   "slug": "adam-and-the-kalla-alugai"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Angry Birds [Y3CUu3OmD60].mp4",
   "cat": "home",
   "emoji": "🐦",
   "title": "Angry Birds",
   "caption": "Angry Birds time! 🐷",
   "added": "2026-09-15",
   "slug": "angry-birds"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "@Home [6sqNfRQghSo].mp4",
   "cat": "home",
   "emoji": "🏡",
   "title": "At Home",
   "caption": "Just a regular day at home, and that's what makes it special.",
   "added": "2026-09-15",
   "slug": "at-home"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Blah Blah Blah Time [4if6M2Dm1As].mp4",
   "cat": "home",
   "emoji": "🗣️",
   "title": "Blah Blah Blah Time",
   "caption": "Chatterbox mode: ON. Somebody had a LOT to say!",
   "added": "2026-09-15",
   "slug": "blah-blah-blah-time"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Caught Milo-Handed [5850IfaQKkU].mp4",
   "cat": "home",
   "emoji": "🥤",
   "title": "Caught Milo-Handed!",
   "caption": "Busted! The great Milo mystery, solved on camera.",
   "added": "2026-09-15",
   "slug": "caught-milo-handed"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Diego Diego Diego ADAM [XH4gMIXFUT8].mp4",
   "cat": "home",
   "emoji": "🐆",
   "title": "Diego, Diego, Diego… ADAM!",
   "caption": "Diego, Diego, Diego… ADAM! (You had to be there. Now you can be.)",
   "added": "2026-09-15",
   "slug": "diego-diego-diego-adam"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Helping with Rubbish Disposal 2 [jBLnkE0OCCo].mp4",
   "cat": "home",
   "emoji": "🗑️",
   "title": "Little Helper: Rubbish Duty (Part 2)",
   "caption": "Chief rubbish-disposal helper, reporting for duty (again).",
   "added": "2026-09-15",
   "slug": "little-helper-rubbish-duty-part-2"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Love You KILI [_1kYSFRgspg].mp4",
   "cat": "home",
   "emoji": "🦜",
   "title": "Love You KILI",
   "caption": "Love you, KILI! 💚",
   "added": "2026-09-15",
   "slug": "love-you-kili"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Mama's new Dishwasher [EpGS4ZgZBJQ].mp4",
   "cat": "home",
   "emoji": "🍽️",
   "title": "Mama's New Dishwasher",
   "caption": "Big news in the kitchen: Mama's new dishwasher!",
   "added": "2026-09-15",
   "slug": "mama-s-new-dishwasher"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Mama, I am Flamingo [G_6fUAxrPhc].mp4",
   "cat": "home",
   "emoji": "🦩",
   "title": "Mama, I Am a Flamingo",
   "caption": "“Mama, I am flamingo!” One leg, maximum elegance.",
   "added": "2026-09-15",
   "slug": "mama-i-am-a-flamingo"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Polkadot Girl [cqO6TxKt5N0].mp4",
   "cat": "home",
   "emoji": "🔴",
   "title": "Polkadot Girl",
   "caption": "Dots, dots, everywhere dots. Meet Polkadot Girl!",
   "added": "2026-09-15",
   "slug": "polkadot-girl"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Sahana in Durra!! [HR7HslRTNmk].mp4",
   "cat": "home",
   "emoji": "✨",
   "title": "Sahana in Durra!!",
   "caption": "Sahana in Durra!! (Two exclamation marks. It was that good.)",
   "added": "2026-09-15",
   "slug": "sahana-in-durra"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "Sleeptime at Nite [FfwOAn_Aj4c].mp4",
   "cat": "home",
   "emoji": "🌙",
   "title": "Sleeptime at Nite",
   "caption": "Shhh… it's sleeptime. (Or is it?)",
   "added": "2026-09-15",
   "slug": "sleeptime-at-nite"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "That's WRONG Dada [RmVfsCiCRpE].mp4",
   "cat": "home",
   "emoji": "🙅‍♀️",
   "title": "That's WRONG, Dada!",
   "caption": "Dada got it wrong, and he was told so. Very clearly.",
   "added": "2026-09-15",
   "slug": "that-s-wrong-dada"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "VIDEO0040 [IEXDMyNIDco].mp4",
   "cat": "phone",
   "emoji": "📼",
   "title": "Phone Video #0040",
   "caption": "A little treasure straight off the phone.",
   "added": "2026-09-15",
   "slug": "phone-video-0040"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "VIDEO0041 [rnTrZ26PmVo].mp4",
   "cat": "phone",
   "emoji": "📼",
   "title": "Phone Video #0041",
   "caption": "A little treasure straight off the phone.",
   "added": "2026-09-15",
   "slug": "phone-video-0041"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "15 Feb11 01 [kure2T0nbk4].mp4",
   "cat": "phone",
   "emoji": "📼",
   "title": "Phone Video · 15 Feb 2011",
   "caption": "A little treasure straight off the phone.",
   "added": "2026-09-15",
   "slug": "phone-video-15-feb-2011",
   "when": "15 February 2011"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "19022011208 [e0d9M_oelbM].mp4",
   "cat": "phone",
   "emoji": "📼",
   "title": "Phone Video · 19 Feb 2011 (a)",
   "caption": "A little treasure straight off the phone.",
   "added": "2026-09-15",
   "slug": "phone-video-19-feb-2011-a",
   "when": "19 February 2011"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "19022011209 [nlya5LKy5O4].mp4",
   "cat": "phone",
   "emoji": "📼",
   "title": "Phone Video · 19 Feb 2011 (b)",
   "caption": "A little treasure straight off the phone.",
   "added": "2026-09-15",
   "slug": "phone-video-19-feb-2011-b",
   "when": "19 February 2011"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "24042011251 [T7MSm3hNCrY].mp4",
   "cat": "phone",
   "emoji": "📼",
   "title": "Phone Video · 24 Apr 2011",
   "caption": "A little treasure straight off the phone.",
   "added": "2026-09-15",
   "slug": "phone-video-24-apr-2011",
   "when": "24 April 2011"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "25042011252 [M2akrDeoqMo].mp4",
   "cat": "phone",
   "emoji": "📼",
   "title": "Phone Video · 25 Apr 2011",
   "caption": "A little treasure straight off the phone.",
   "added": "2026-09-15",
   "slug": "phone-video-25-apr-2011",
   "when": "25 April 2011"
  },
  {
   "kind": "video",
   "folder": "Video",
   "file": "30012011045 [tqA-tpnakbA].mp4",
   "cat": "phone",
   "emoji": "📼",
   "title": "Phone Video · 30 Jan 2011",
   "caption": "A little treasure straight off the phone.",
   "added": "2026-09-15",
   "slug": "phone-video-30-jan-2011",
   "when": "30 January 2011"
  }
 ]
};
